name: Download Torrent

on:
  workflow_dispatch:
    inputs:
      MAGNET:
        description: 'magnet:?xt=urn:btih:57f2957e762cca5a279728153aabc6dbb02c6062&dn=Infinite%20Stratos%20%28manga%20complete%29%20%2B%20LN%27s%20v01-12%20%28ongoing%29&tr=http%3A%2F%2Fnyaa.tracker.wf%3A7777%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Download Torrent
        run: aria2c --seed-time=0 "${{ github.event.inputs.MAGNET }}"

      - name: Zip Downloaded Torrent
        run: zip -r torrent.zip *

      - name: Create Release on GitHub
        uses: softprops/action-gh-release@v3
        with:
          draft: true
          files: torrent.zip
