name: Download Torrent

on:
  workflow_dispatch:
    inputs:
      MAGNET:
        description: 'Magnet'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Download Torrent
        run: aria2c --seed-time=0 "${{ github.event.inputs.MAGNET }}"

      - name: Zip Downloaded Torrent
        run: zip -r torrent.zip *

      - name: Create Release on GitHub
        uses: softprops/action-gh-release@v3
        with:
          draft: true
          files: torrent.zip
